import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { FC, PropsWithChildren } from "react";
import { Locale } from "@/i18n";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps extends PropsWithChildren {
  params: {locale: Locale};
}

const RootLayout: FC<RootLayoutProps> = ({
  children,
  params: { locale }
}) => (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  );

export default RootLayout;
